apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-argocd-test
data:
  nginx.conf: '
events {
}
http {
   server {
       listen 80;
       location / {
           return 200 "Nginx version: $nginx_version";
       }
   }
}
'
